# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dodrqpRhyHogsVJDQWOqkpFLJ6HZgx1S

1. Mapa de Fabricantes, Importadores y Reparadores
"""

!pip install xlrd -q

!pip install geopy folium

import os
import glob
import pandas as pd
import folium
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import folium

archivo = f"https://docs.google.com/spreadsheets/d/1iEJl5proYp_-wZHhXMPmzOdNfH4h6EHfDOi1ikCQsok/edit?usp=sharing"
sheet_id = archivo.split("/d/")[1].split("/")[0]

archivo_csv_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

df = pd.read_csv(archivo_csv_url)

df.head()

df.columns

df["Inscripto como"].value_counts()

geolocator = Nominatim(user_agent="mapa_registros_colab")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1.5)

df['Direccion_Completa'] = df['Dirección'].astype(str) +", Montevideo" +", Uruguay"

print("Buscando coordenadas... esto puede tardar un poco dependiendo de la cantidad de registros.")
df['Ubicacion'] = df['Direccion_Completa'].apply(geocode)

df['Latitud'] = df['Ubicacion'].apply(lambda loc: loc.latitude if loc else None)
df['Longitud'] = df['Ubicacion'].apply(lambda loc: loc.longitude if loc else None)

df_mapa = df.dropna(subset=['Latitud', 'Longitud']).copy()
registros_perdidos = len(df) - len(df_mapa)
print(f"Búsqueda finalizada. Se ubicaron {len(df_mapa)} registros. No se encontraron coordenadas para {registros_perdidos} registros.")

registros_no_encontrados = df[
    df['Latitud'].isna() | df['Longitud'].isna()
]
for empresa in registros_no_encontrados['Razón Social']:
    print(empresa)

# Iniciamos el mapa centrado en Montevideo (Latitud -34.9011, Longitud -56.1645)
mapa = folium.Map(location=[-34.9011, -56.1645], zoom_start=12)

# --- PASO FINAL: Agregar los marcadores y mostrar el mapa ---

for index, row in df_mapa.iterrows():

    nombre_empresa = row.get('Razón Social', 'Empresa sin nombre')
    tipo_inscripcion = row.get('Inscripto como', 'Sin definir')
    origen = row.get('Origen', 'Desconocido')

    # CSS inyectado para un diseño tipo tarjeta (bordes redondeados, sombra, fuente moderna)
    html_popup = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; min-width: 220px; padding: 5px;">
        <h4 style="margin-top: 0; margin-bottom: 8px; color: #2c3e50; font-size: 16px;">{nombre_empresa}</h4>
        <div style="background-color: #f8f9fa; padding: 8px; border-radius: 6px; border-left: 4px solid #3498db;">
            <b style="color: #555; font-size: 12px; text-transform: uppercase;">Categoría:</b><br>
            <span style="color: #333; font-size: 14px; font-weight: bold;">{tipo_inscripcion}</span>
        </div>
        <div style="margin-top: 10px; font-size: 11px; color: #7f8c8d; text-align: right;">
            <i>Fuente: {origen}</i>
        </div>
    </div>
    """

    color_pin = 'blue'
    tipo_str = str(tipo_inscripcion).lower()

    if 'importador reparador' in tipo_str or 'ambos' in tipo_str:
        color_pin = 'purple'
    elif 'importador' in tipo_str:
        color_pin = 'green'
    elif 'reparador' in tipo_str:
        color_pin = 'orange'

    # Cambiamos a íconos de FontAwesome (prefix='fa')
    icono_forma = 'star' if origen == 'Sugerido por LATU' else 'info'

    folium.Marker(
        location=[row['Latitud'], row['Longitud']],
        popup=folium.Popup(html_popup, max_width=300),
        icon=folium.Icon(color=color_pin, icon=icono_forma, prefix='fa')
    ).add_to(mapa)

from folium import plugins
plugins.Fullscreen(position='topright', title='Pantalla Completa', title_cancel='Salir').add_to(mapa)

mapa.save('index.html')

mapa